export const IpcChannels = {
  PROXY_START: 'proxy:start',
  PROXY_STOP: 'proxy:stop',
  PROXY_GET_STATUS: 'proxy:getStatus',
  PROXY_STATUS_CHANGED: 'proxy:statusChanged',
  PROXY_GET_STATISTICS: 'proxy:getStatistics',
  PROXY_RESET_STATISTICS: 'proxy:resetStatistics',

  CONFIG_GET: 'config:get',
  CONFIG_UPDATE: 'config:update',

  STORE_GET: 'store:get',
  STORE_SET: 'store:set',
  STORE_DELETE: 'store:delete',
  STORE_CLEAR_ALL: 'store:clearAll',

  PROVIDERS_GET_ALL: 'providers:getAll',
  PROVIDERS_GET_BUILTIN: 'providers:getBuiltin',
  PROVIDERS_ADD: 'providers:add',
  PROVIDERS_UPDATE: 'providers:update',
  PROVIDERS_DELETE: 'providers:delete',
  PROVIDERS_CHECK_STATUS: 'providers:checkStatus',
  PROVIDERS_CHECK_ALL_STATUS: 'providers:checkAllStatus',
  PROVIDERS_DUPLICATE: 'providers:duplicate',
  PROVIDERS_EXPORT: 'providers:export',
  PROVIDERS_IMPORT: 'providers:import',

  ACCOUNTS_GET_ALL: 'accounts:getAll',
  ACCOUNTS_GET_BY_ID: 'accounts:getById',
  ACCOUNTS_GET_BY_PROVIDER: 'accounts:getByProvider',
  ACCOUNTS_ADD: 'accounts:add',
  ACCOUNTS_UPDATE: 'accounts:update',
  ACCOUNTS_DELETE: 'accounts:delete',
  ACCOUNTS_VALIDATE: 'accounts:validate',
  ACCOUNTS_VALIDATE_TOKEN: 'accounts:validateToken',
  ACCOUNTS_GET_CREDITS: 'accounts:getCredits',

  OAUTH_START_LOGIN: 'oauth:startLogin',
  OAUTH_CANCEL_LOGIN: 'oauth:cancelLogin',
  OAUTH_CALLBACK: 'oauth:callback',
  OAUTH_LOGIN_WITH_TOKEN: 'oauth:loginWithToken',
  OAUTH_VALIDATE_TOKEN: 'oauth:validateToken',
  OAUTH_REFRESH_TOKEN: 'oauth:refreshToken',
  OAUTH_GET_STATUS: 'oauth:getStatus',
  OAUTH_PROGRESS: 'oauth:progress',
  OAUTH_START_IN_APP_LOGIN: 'oauth:startInAppLogin',
  OAUTH_CANCEL_IN_APP_LOGIN: 'oauth:cancelInAppLogin',
  OAUTH_IN_APP_LOGIN_STATUS: 'oauth:inAppLoginStatus',

  LOGS_GET: 'logs:get',
  LOGS_GET_STATS: 'logs:getStats',
  LOGS_GET_TREND: 'logs:getTrend',
  LOGS_GET_ACCOUNT_TREND: 'logs:getAccountTrend',
  LOGS_CLEAR: 'logs:clear',
  LOGS_EXPORT: 'logs:export',
  LOGS_GET_BY_ID: 'logs:getById',
  LOGS_NEW_LOG: 'logs:newLog',

  APP_GET_VERSION: 'app:getVersion',
  APP_MINIMIZE: 'app:minimize',
  APP_MAXIMIZE: 'app:maximize',
  APP_CLOSE: 'app:close',
  APP_SHOW_WINDOW: 'app:showWindow',
  APP_HIDE_WINDOW: 'app:hideWindow',
  APP_OPEN_EXTERNAL: 'app:openExternal',

  PROMPTS_GET_ALL: 'prompts:getAll',
  PROMPTS_GET_BUILTIN: 'prompts:getBuiltin',
  PROMPTS_GET_CUSTOM: 'prompts:getCustom',
  PROMPTS_GET_BY_ID: 'prompts:getById',
  PROMPTS_ADD: 'prompts:add',
  PROMPTS_UPDATE: 'prompts:update',
  PROMPTS_DELETE: 'prompts:delete',
  PROMPTS_GET_BY_TYPE: 'prompts:getByType',

  SESSION_GET_CONFIG: 'session:getConfig',
  SESSION_UPDATE_CONFIG: 'session:updateConfig',
  SESSION_GET_ALL: 'session:getAll',
  SESSION_GET_ACTIVE: 'session:getActive',
  SESSION_GET_BY_ID: 'session:getById',
  SESSION_GET_BY_ACCOUNT: 'session:getByAccount',
  SESSION_GET_BY_PROVIDER: 'session:getByProvider',
  SESSION_DELETE: 'session:delete',
  SESSION_CLEAR_ALL: 'session:clearAll',
  SESSION_CLEAN_EXPIRED: 'session:cleanExpired',
} as const

export type IpcChannel = (typeof IpcChannels)[keyof typeof IpcChannels]
